### ISSUE TITLE
Getting Error

### ISSUE THREAD

**Issue by leocas18** [neuralpain/qbactivator#1]
Hello
At first, I tried the activator and got ""Patch file not found. Patcher will now close."
The patcher did run and while the patcher was running I opened the pos software and got invalid product # and could not proceed to enter the activation code. 
I am on windows 11, I have tried other version activators before on windows 11 and got invalid product # as well. I could only get activated with early versions of windows 10. Your activator seems to have the same issue as other activators. I will try your activator on windows 10.

**Comment by neuralpain** [comment]
`qbactivator.cmd` and `qbpatch.dat` are both required for proper activation. Extract these files to the same location and run `qbactivator.cmd`. When the patcher is started it will look in the current location for `qbpatch.dat`. If it is not found, the patch will not continue.

For the POS software, there should be two keys for each version. There also a weird bug where the first key you try will not work but it accepts the other key that you enter on the second attempt. I'm working on mitigating these kinds of errors in the activation.

**Comment by leocas18** [comment]
> Hey, thanks for trying it out.
> 
> > At first, I tried the activator and got ""Patch file not found. Patcher will now close."
> 
> `qbactivator.cmd` and `qbpatch.dat` are both required for proper activation. You should have these two files extracted to the same location and run the activation script. When the script is started it will look in the current location for `qbpatch.dat`. If it is not found, the patch will not continue.
> 
> > while the patcher was running I opened the pos software and got invalid product #
> 
> I'm working on a fix for this issue. Stay posted for the update.

**Comment by leocas18** [comment]
I appreciate you looking into the issue, I am trying your new activator and will let you know the outcome.

**Comment by neuralpain** [comment]
I just published a release `v0.17.1` with updated keys for POS v11 and v12. You can [download it here](https://github.com/neuralpain/qbactivator/releases/download/v0.17.1/qbactivator-0.17.1.zip) if you are installing any of those versions.

**Comment by 861861** [comment]
Hello Sir,
I have tried the qbactivator for V19. I still get the same messages, patcher is not found and if I run the script with powershell, I get the message "error patch file is corrupted" please contact...

There seems to be something wrong..

![qb patch](https://user-images.githubusercontent.com/123078578/213439742-417b8768-c987-4d7d-9739-26e365dfd142.png)
